### ISSUE TITLE
求助！更新最新版本后升级数据库失败，已安装nonebot-session-to-uninfo

### ISSUE THREAD

**Issue by dmnoobcoder** [noneplugin/nonebot-plugin-memes-api#9]
以下是详细报错信息

root@nas:/home/su/qqbot/nl_annon# nb orm upgrade
Using python: /home/su/qqbot/nl_annon/.venv/bin/python
12-31 20:39:05 [SUCCESS] nonebot | NoneBot is initializing...
12-31 20:39:05 [INFO] nonebot | Current Env: prod
12-31 20:39:06 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_alconna:uniseg" from "nonebot_plugin_alconna.uniseg"
12-31 20:39:06 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_alconna"
12-31 20:39:06 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_oddtext"
12-31 20:39:06 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_alconna"
12-31 20:39:07 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_ottohzys"
12-31 20:39:07 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_sayoroll"
12-31 20:39:07 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_treehelp"
12-31 20:39:07 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_waiter"
12-31 20:39:07 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_userinfo"
12-31 20:39:07 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_uninfo"
12-31 20:39:07 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_localstore"
12-31 20:39:07 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_orm"
12-31 20:39:08 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_memes_api"
12-31 20:39:08 [INFO] nonebot_plugin_random_stereotypes | Using api meme source
12-31 20:39:08 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_random_stereotypes"
12-31 20:39:08 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_today_waifu"
12-31 20:39:08 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_emojimix"
12-31 20:39:08 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_memes_api"
12-31 20:39:08 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_wordle"
12-31 20:39:08 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_handle"
12-31 20:39:08 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_uninfo"
12-31 20:39:08 [INFO] nonebot_plugin_autoreply | 加载回复配置 reply.yml 成功
12-31 20:39:08 [INFO] nonebot_plugin_autoreply | 加载回复配置完毕，成功 1 个，失败 0 个
12-31 20:39:08 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_autoreply"
12-31 20:39:08 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_minesweeper"
12-31 20:39:09 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_fakepic"
12-31 20:39:09 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_status"
12-31 20:39:09 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_dicky_pk"
Traceback (most recent call last):
  File "<string>", line 27, in <module>
  File "/home/su/qqbot/nl_annon/.venv/lib/python3.12/site-packages/nonebot_plugin_orm/__main__.py", line 283, in main
    orm(*args, **kwargs)
  File "/home/su/qqbot/nl_annon/.venv/lib/python3.12/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/su/qqbot/nl_annon/.venv/lib/python3.12/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/home/su/qqbot/nl_annon/.venv/lib/python3.12/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/su/qqbot/nl_annon/.venv/lib/python3.12/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/su/qqbot/nl_annon/.venv/lib/python3.12/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/su/qqbot/nl_annon/.venv/lib/python3.12/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/su/qqbot/nl_annon/.venv/lib/python3.12/site-packages/nonebot_plugin_orm/__main__.py", line 86, in wrapper
    return f(ctx.obj, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/su/qqbot/nl_annon/.venv/lib/python3.12/site-packages/nonebot_plugin_orm/__main__.py", line 175, in upgrade
    return migrate.upgrade(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/su/qqbot/nl_annon/.venv/lib/python3.12/site-packages/nonebot_plugin_orm/migrate.py", line 662, in upgrade
    script.run_env()
  File "/home/su/qqbot/nl_annon/.venv/lib/python3.12/site-packages/alembic/script/base.py", line 586, in run_env
    util.load_python_file(self.dir, "env.py")
  File "/home/su/qqbot/nl_annon/.venv/lib/python3.12/site-packages/alembic/util/pyfiles.py", line 95, in load_python_file
    module = load_module_py(module_id, path)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/su/qqbot/nl_annon/.venv/lib/python3.12/site-packages/alembic/util/pyfiles.py", line 113, in load_module_py
    spec.loader.exec_module(module)  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/su/qqbot/nl_annon/.venv/lib/python3.12/site-packages/nonebot_plugin_orm/templates/generic/env.py", line 88, in <module>
    asyncio.run(coro)
  File "/usr/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/su/qqbot/nl_annon/.venv/lib/python3.12/site-packages/nonebot_plugin_orm/templates/generic/env.py", line 79, in run_migrations_online
    await connection.run_sync(do_run_migrations)
  File "/home/su/qqbot/nl_annon/.venv/lib/python3.12/site-packages/sqlalchemy/ext/asyncio/engine.py", line 886, in run_sync
    return await greenlet_spawn(
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/su/qqbot/nl_annon/.venv/lib/python3.12/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 203, in greenlet_spawn
    result = context.switch(value)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/home/su/qqbot/nl_annon/.venv/lib/python3.12/site-packages/nonebot_plugin_orm/templates/generic/env.py", line 69, in do_run_migrations
    context.run_migrations()
  File "<string>", line 8, in run_migrations
  File "/home/su/qqbot/nl_annon/.venv/lib/python3.12/site-packages/alembic/runtime/environment.py", line 946, in run_migrations
    self.get_context().run_migrations(**kw)
  File "/home/su/qqbot/nl_annon/.venv/lib/python3.12/site-packages/alembic/runtime/migration.py", line 628, in run_migrations
    step.migration_fn(**kw)
  File "/tmp/tmpku0juxch/nonebot_plugin_memes_api/ba63ee20dbc1_data_migrate.py", line 101, in upgrade
  File "/tmp/tmpku0juxch/nonebot_plugin_memes_api/ba63ee20dbc1_data_migrate.py", line 50, in data_migrate
  File "/home/su/qqbot/nl_annon/.venv/lib/python3.12/site-packages/nonebot_session_to_uninfo/__init__.py", line 18, in check_tables
    raise ValueError("表 nonebot_plugin_uninfo_botmodel 不存在")
ValueError: 表 nonebot_plugin_uninfo_botmodel 不存在

**Comment by MeetWq** [comment]
你需要安装 nonebot_plugin_uninfo 0.6.0 以上版本

**Comment by dmnoobcoder** [comment]
新年快乐！
确认了一下安装的是0.6.3版本的nonebot_plugin_uninfo

root@nas:/home/su/qqbot/nl_annon# nb plugin
[?] What do you want to do? Update nonebot plugin.
[?] Plugin name to update: nonebot-plugin-uninfo
Using python: /home/su/qqbot/nl_annon/.venv/bin/python
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Collecting nonebot-plugin-uninfo
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/0f/86/53c8faf463dd888e012c674bf5e1fe2eeaab444e7844c49e8b6aaf77d63b/nonebot_plugin_uninfo-0.6.3-py3-none-any.whl (54 kB)
Requirement already satisfied: nonebot2>=2.3.0 in ./.venv/lib/python3.12/site-packages (from nonebot-plugin-uninfo) (2.4.0)
Requirement already satisfied: importlib-metadata>=4.13.0 in ./.venv/lib/python3.12/site-packages (from nonebot-plugin-uninfo) (8.5.0)
Requirement already satisfied: zipp>=3.20 in ./.venv/lib/python3.12/site-packages (from importlib-metadata>=4.13.0->nonebot-plugin-uninfo) (3.20.2)
Requirement already satisfied: anyio<5.0.0,>=4.4.0 in ./.venv/lib/python3.12/site-packages (from nonebot2>=2.3.0->nonebot-plugin-uninfo) (4.6.2.post1)
Requirement already satisfied: exceptiongroup<2.0.0,>=1.2.2 in ./.venv/lib/python3.12/site-packages (from nonebot2>=2.3.0->nonebot-plugin-uninfo) (1.2.2)
Requirement already satisfied: loguru<1.0.0,>=0.6.0 in ./.venv/lib/python3.12/site-packages (from nonebot2>=2.3.0->nonebot-plugin-uninfo) (0.7.2)
Requirement already satisfied: pydantic!=2.5.0,!=2.5.1,<3.0.0,>=1.10.0 in ./.venv/lib/python3.12/site-packages (from nonebot2>=2.3.0->nonebot-plugin-uninfo) (2.9.2)
Requirement already satisfied: pygtrie<3.0.0,>=2.4.1 in ./.venv/lib/python3.12/site-packages (from nonebot2>=2.3.0->nonebot-plugin-uninfo) (2.5.0)
Requirement already satisfied: python-dotenv<2.0.0,>=0.21.0 in ./.venv/lib/python3.12/site-packages (from nonebot2>=2.3.0->nonebot-plugin-uninfo) (1.0.1)
Requirement already satisfied: typing-extensions<5.0.0,>=4.4.0 in ./.venv/lib/python3.12/site-packages (from nonebot2>=2.3.0->nonebot-plugin-uninfo) (4.12.2)
Requirement already satisfied: yarl<2.0.0,>=1.7.2 in ./.venv/lib/python3.12/site-packages (from nonebot2>=2.3.0->nonebot-plugin-uninfo) (1.15.3)
Requirement already satisfied: idna>=2.8 in ./.venv/lib/python3.12/site-packages (from anyio<5.0.0,>=4.4.0->nonebot2>=2.3.0->nonebot-plugin-uninfo) (3.10)
Requirement already satisfied: sniffio>=1.1 in ./.venv/lib/python3.12/site-packages (from anyio<5.0.0,>=4.4.0->nonebot2>=2.3.0->nonebot-plugin-uninfo) (1.3.1)
Requirement already satisfied: annotated-types>=0.6.0 in ./.venv/lib/python3.12/site-packages (from pydantic!=2.5.0,!=2.5.1,<3.0.0,>=1.10.0->nonebot2>=2.3.0->nonebot-plugin-uninfo) (0.7.0)
Requirement already satisfied: pydantic-core==2.23.4 in ./.venv/lib/python3.12/site-packages (from pydantic!=2.5.0,!=2.5.1,<3.0.0,>=1.10.0->nonebot2>=2.3.0->nonebot-plugin-uninfo) (2.23.4)
Requirement already satisfied: multidict>=4.0 in ./.venv/lib/python3.12/site-packages (from yarl<2.0.0,>=1.7.2->nonebot2>=2.3.0->nonebot-plugin-uninfo) (6.1.0)
Requirement already satisfied: propcache>=0.2.0 in ./.venv/lib/python3.12/site-packages (from yarl<2.0.0,>=1.7.2->nonebot2>=2.3.0->nonebot-plugin-uninfo) (0.2.0)
Installing collected packages: nonebot-plugin-uninfo
Successfully installed nonebot-plugin-uninfo-0.6.3
root@nas:/home/su/qqbot/nl_annon# nb orm upgrade
Using python: /home/su/qqbot/nl_annon/.venv/bin/python
01-01 00:12:59 [SUCCESS] nonebot | NoneBot is initializing...
01-01 00:12:59 [INFO] nonebot | Current Env: prod
01-01 00:13:00 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_alconna:uniseg" from "nonebot_plugin_alconna.uniseg"
01-01 00:13:00 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_alconna"
01-01 00:13:00 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_waiter"
01-01 00:13:00 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_uninfo"
01-01 00:13:00 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_localstore"
01-01 00:13:01 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_orm"
01-01 00:13:02 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_memes_api"
01-01 00:13:02 [INFO] nonebot_plugin_autoreply | 加载回复配置 reply.yml 成功
01-01 00:13:02 [INFO] nonebot_plugin_autoreply | 加载回复配置完毕，成功 1 个，失败 0 个
01-01 00:13:02 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_autoreply"
01-01 00:13:02 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_ottohzys"
01-01 00:13:02 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_today_waifu"
01-01 00:13:02 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_alconna"
01-01 00:13:02 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_minesweeper"
01-01 00:13:02 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_userinfo"
01-01 00:13:02 [INFO] nonebot_plugin_random_stereotypes | Using api meme source
01-01 00:13:02 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_random_stereotypes"
01-01 00:13:02 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_emojimix"
01-01 00:13:02 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_treehelp"
01-01 00:13:02 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_oddtext"
01-01 00:13:02 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_dicky_pk"
01-01 00:13:02 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_wordle"
01-01 00:13:02 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_sayoroll"
01-01 00:13:02 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_status"
01-01 00:13:02 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_handle"
01-01 00:13:02 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_fakepic"
Traceback (most recent call last):
  File "<string>", line 27, in <module>
  File "/home/su/qqbot/nl_annon/.venv/lib/python3.12/site-packages/nonebot_plugin_orm/__main__.py", line 283, in main
    orm(*args, **kwargs)
  File "/home/su/qqbot/nl_annon/.venv/lib/python3.12/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/su/qqbot/nl_annon/.venv/lib/python3.12/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/home/su/qqbot/nl_annon/.venv/lib/python3.12/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/su/qqbot/nl_annon/.venv/lib/python3.12/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/su/qqbot/nl_annon/.venv/lib/python3.12/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/su/qqbot/nl_annon/.venv/lib/python3.12/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/su/qqbot/nl_annon/.venv/lib/python3.12/site-packages/nonebot_plugin_orm/__main__.py", line 86, in wrapper
    return f(ctx.obj, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/su/qqbot/nl_annon/.venv/lib/python3.12/site-packages/nonebot_plugin_orm/__main__.py", line 175, in upgrade
    return migrate.upgrade(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/su/qqbot/nl_annon/.venv/lib/python3.12/site-packages/nonebot_plugin_orm/migrate.py", line 662, in upgrade
    script.run_env()
  File "/home/su/qqbot/nl_annon/.venv/lib/python3.12/site-packages/alembic/script/base.py", line 586, in run_env
    util.load_python_file(self.dir, "env.py")
  File "/home/su/qqbot/nl_annon/.venv/lib/python3.12/site-packages/alembic/util/pyfiles.py", line 95, in load_python_file
    module = load_module_py(module_id, path)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/su/qqbot/nl_annon/.venv/lib/python3.12/site-packages/alembic/util/pyfiles.py", line 113, in load_module_py
    spec.loader.exec_module(module)  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/su/qqbot/nl_annon/.venv/lib/python3.12/site-packages/nonebot_plugin_orm/templates/generic/env.py", line 88, in <module>
    asyncio.run(coro)
  File "/usr/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/su/qqbot/nl_annon/.venv/lib/python3.12/site-packages/nonebot_plugin_orm/templates/generic/env.py", line 79, in run_migrations_online
    await connection.run_sync(do_run_migrations)
  File "/home/su/qqbot/nl_annon/.venv/lib/python3.12/site-packages/sqlalchemy/ext/asyncio/engine.py", line 886, in run_sync
    return await greenlet_spawn(
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/su/qqbot/nl_annon/.venv/lib/python3.12/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 203, in greenlet_spawn
    result = context.switch(value)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/home/su/qqbot/nl_annon/.venv/lib/python3.12/site-packages/nonebot_plugin_orm/templates/generic/env.py", line 69, in do_run_migrations
    context.run_migrations()
  File "<string>", line 8, in run_migrations
  File "/home/su/qqbot/nl_annon/.venv/lib/python3.12/site-packages/alembic/runtime/environment.py", line 946, in run_migrations
    self.get_context().run_migrations(**kw)
  File "/home/su/qqbot/nl_annon/.venv/lib/python3.12/site-packages/alembic/runtime/migration.py", line 628, in run_migrations
    step.migration_fn(**kw)
  File "/tmp/tmp5w7sar1k/nonebot_plugin_memes_api/ba63ee20dbc1_data_migrate.py", line 101, in upgrade
  File "/tmp/tmp5w7sar1k/nonebot_plugin_memes_api/ba63ee20dbc1_data_migrate.py", line 50, in data_migrate
  File "/home/su/qqbot/nl_annon/.venv/lib/python3.12/site-packages/nonebot_session_to_uninfo/__init__.py", line 18, in check_tables
    raise ValueError("表 nonebot_plugin_uninfo_botmodel 不存在")
ValueError: 表 nonebot_plugin_uninfo_botmodel 不存在
root@nas:/home/su/qqbot/nl_annon#

**Comment by MeetWq** [comment]
你运行一下 `nb orm show` 看看结果

**Comment by dmnoobcoder** [comment]
hi

root@nas:/home/su/qqbot/nl_annon# nb orm show
Using python: /home/su/qqbot/nl_annon/.venv/bin/python
01-01 22:07:54 [SUCCESS] nonebot | NoneBot is initializing...
01-01 22:07:54 [INFO] nonebot | Current Env: prod
01-01 22:07:55 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_alconna:uniseg" from "nonebot_plugin_alconna.uniseg"
01-01 22:07:55 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_alconna"
01-01 22:07:55 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_waiter"
01-01 22:07:55 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_uninfo"
01-01 22:07:55 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_localstore"
01-01 22:07:56 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_orm"
01-01 22:07:57 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_memes_api"
01-01 22:07:57 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_userinfo"
01-01 22:07:57 [INFO] nonebot_plugin_random_stereotypes | Using api meme source
01-01 22:07:57 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_random_stereotypes"
01-01 22:07:57 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_alconna"
01-01 22:07:57 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_oddtext"
01-01 22:07:57 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_status"
01-01 22:07:57 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_wordle"
01-01 22:07:57 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_sayoroll"
01-01 22:07:57 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_emojimix"
01-01 22:07:57 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_handle"
01-01 22:07:57 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_today_waifu"
01-01 22:07:57 [INFO] nonebot_plugin_autoreply | 加载回复配置 reply.yml 成功
01-01 22:07:57 [INFO] nonebot_plugin_autoreply | 加载回复配置完毕，成功 1 个，失败 0 个
01-01 22:07:57 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_autoreply"
01-01 22:07:57 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_minesweeper"
01-01 22:07:57 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_fakepic"
01-01 22:07:58 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_ottohzys"
01-01 22:07:58 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_treehelp"
01-01 22:07:58 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_dicky_pk"
Rev: a82b5f32c60f (head)
Parent: <base>
Also depends on: fff55366306e
Branch names: nonebot_plugin_memes
Path: /tmp/tmpfbljeokm/nonebot_plugin_memes/a82b5f32c60f_init_db.py

    init_db

    迁移 ID: a82b5f32c60f
    父迁移:
    创建时间: 2024-08-12 22:16:13.840860

Rev: 71a72119935f (head)
Parent: fff55366306e
Branch names: nonebot_plugin_session_orm
Path: /tmp/tmpfbljeokm/nonebot_plugin_session_orm/71a72119935f_data_migrate.py

    data_migrate

    修订 ID: 71a72119935f
    父修订: fff55366306e
    创建时间: 2023-10-12 13:31:08.788371

Rev: dc81a3212383 (head)
Parent: <base>
Branch names: nonebot_plugin_boardgame
Path: /tmp/tmpfbljeokm/nonebot_plugin_boardgame/dc81a3212383_init_db.py

    init_db

    修订 ID: dc81a3212383
    父修订:
    创建时间: 2023-10-20 14:29:37.795528

Rev: a9a3810efa4a (head)
Parent: <base>
Branch names: nonebot_plugin_alchelper
Path: /tmp/tmpfbljeokm/nonebot_plugin_alchelper/a9a3810efa4a_0_5_0.py

    0_5_0

    迁移 ID: a9a3810efa4a
    父迁移:
    创建时间: 2024-03-17 15:44:38.104506

Rev: fdc15c338ecc (head)
Parent: 0b2f6bf54834
Branch names: nonebot_plugin_shindan
Path: /tmp/tmpfbljeokm/nonebot_plugin_shindan/fdc15c338ecc_shindan_id_type.py

    shindan_id_type

    迁移 ID: fdc15c338ecc
    父迁移: 0b2f6bf54834
    创建时间: 2024-03-03 13:47:11.231471

Rev: aa8ad49a7a47 (head)
Parent: <base>
Also depends on: fff55366306e
Branch names: nonebot_plugin_memes_api
Path: /tmp/tmpfbljeokm/nonebot_plugin_memes_api/aa8ad49a7a47_init_db.py

    init_db
    迁移 ID: aa8ad49a7a47
    父迁移:
    创建时间: 2024-08-12 22:50:10.114514

Rev: 1ad5a608c9e0
Parent: <base>
Branch names: nonebot_plugin_memes_api_v2
Path: /tmp/tmpfbljeokm/nonebot_plugin_memes_api/1ad5a608c9e0_init_db.py

    init_db

    迁移 ID: 1ad5a608c9e0
    父迁移:
    创建时间: 2024-12-23 21:14:22.421381

root@nas:/home/su/qqbot/nl_annon#

**Comment by dmnoobcoder** [comment]
已解决：
输入nb orm downgrade base 后重新nb orm upgrade

**Comment by dmnoobcoder** [comment]
this issue can be closed
